name: readable
description: A new way to organize your favorite books.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  sqflite: ^2.3.3+2
  path_provider: ^2.1.4
  path: ^1.9.0

dev_dependencies:
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.png
    - assets/images/book_hero.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen.png
  android: true
  ios: true
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/readable.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/readable.png"
